services:
  db:
    image: postgres:16-alpine
    container_name: course-platform-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=course_platform
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d course_platform" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: src/API/Dockerfile
    container_name: course-platform-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=course_platform;Username=postgres;Password=postgres
      - JWT__Key=YourSuperSecretKeyWithAtLeast32Characters!
      - JWT__Issuer=OnlineCoursePlatform
      - JWT__Audience=OnlineCoursePlatform
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
    ports:
      - "5239:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./src/Frontend
      dockerfile: Dockerfile
    container_name: course-platform-frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data:
